"""Constants for Week Planner."""
DOMAIN = "week_planner"
NAME = "Week Planner"
VERSION = "0.5.3-dev.4"

CONF_WEATHER_ENTITY = "weather_entity"
CONF_CALENDAR_ENTITIES = "calendar_entities"
CONF_CALENDAR_COLORS = "calendar_colors"
CONF_CALENDAR_DISPLAY_MODES = "calendar_display_modes"
CONF_CALENDAR_AVATARS = "calendar_avatars"
CONF_HISTORY_SOURCES = "history_sources"
CONF_ENERGY_ENTITY = "energy_entity"
CONF_SHOW_ENERGY_PRICES = "show_energy_prices"
CONF_WEATHER_DISPLAY = "weather_display"
CONF_SHOW_WEEK_NUMBER = "show_week_number"
CONF_DEFAULT_SCROLL_HOUR = "default_scroll_hour"
CONF_SCROLL_MODE = "scroll_mode"
CONF_SHOW_SUN_MARKERS = "show_sun_markers"
CONF_SHOW_MOON_MARKERS = "show_moon_markers"
CONF_ENLARGE_TODAY = "enlarge_today"
CONF_VIEW_MODE = "view_mode"

SCROLL_MODE_NONE = "none"
SCROLL_MODE_FIXED = "fixed"
SCROLL_MODE_FOLLOW_NOW = "follow_now"

VIEW_MODE_WEEK = "week"
VIEW_MODE_ROLLING = "rolling"

WEATHER_DISPLAY_HOURLY = "hourly"
WEATHER_DISPLAY_DAILY = "daily"
WEATHER_DISPLAY_BOTH = "both"
WEATHER_DISPLAY_NONE = "none"

DISPLAY_AUTO = "auto"
DISPLAY_RIBBON = "ribbon"
DISPLAY_TIMELINE = "timeline"

PANEL_URL = "week-planner"
PANEL_ELEMENT = "week-planner-panel"
STATIC_URL = "/week_planner_static"
