"""Constants for Week Planner."""
DOMAIN = "week_planner"
NAME = "Week Planner"
VERSION = "0.5.3-dev.21"

CONF_WEATHER_ENTITY = "weather_entity"
CONF_CALENDAR_ENTITIES = "calendar_entities"
CONF_CALENDAR_COLORS = "calendar_colors"
CONF_CALENDAR_DISPLAY_MODES = "calendar_display_modes"
CONF_CALENDAR_AVATARS = "calendar_avatars"