from pathlib import Path

path = Path('custom_components/week_planner/__init__.py')
text = path.read_text(encoding='utf-8')
start = text.index('async def _async_ensure_lovelace_resource')
end = text.index('\ndef _dashboard_config()', start)
new = '''async def _async_ensure_lovelace_resource(hass: HomeAssistant) -> None:\n    \"\"\"Ensure exactly one current Week Planner Lovelace resource exists.\"\"\"\n    lovelace_data = hass.data.get(LOVELACE_DATA)\n    if lovelace_data is None:\n        raise RuntimeError(\"Lovelace is not initialized\")\n\n    resources = lovelace_data.resources\n    if not isinstance(resources, ResourceStorageCollection):\n        _LOGGER.warning(\n            \"Week Planner cannot automatically manage its frontend resource because \"\n            \"Lovelace resources are not in storage mode\"\n        )\n        return\n\n    await resources.async_get_info()\n    current_url = f\"{_RESOURCE_BASE_URL}?v={VERSION}\"\n    matches = []\n    for item in list(resources.async_items()):\n        url = str(item.get(CONF_URL, \"\"))\n        # Match both relative and absolute URLs so an older manually-created\n        # Week Planner resource cannot survive upgrades alongside the managed one.\n        base = url.split(\"?\", 1)[0].rstrip(\"/\")\n        if base == _RESOURCE_BASE_URL or base.endswith(_RESOURCE_BASE_URL):\n            matches.append(item)\n\n    if not matches:\n        await resources.async_create_item(\n            {CONF_RESOURCE_TYPE_WS: \"module\", CONF_URL: current_url}\n        )\n        _LOGGER.info(\"Registered Week Planner Lovelace resource %s\", current_url)\n        return\n\n    primary = matches[0]\n    if primary.get(CONF_URL) != current_url or primary.get(CONF_RESOURCE_TYPE_WS) != \"module\":\n        await resources.async_update_item(\n            primary[\"id\"],\n            {CONF_RESOURCE_TYPE_WS: \"module\", CONF_URL: current_url},\n        )\n        _LOGGER.info(\"Updated Week Planner Lovelace resource to %s\", current_url)\n\n    # A duplicate stale resource can still make Lovelace request an old URL.\n    # Keep the first managed resource and remove every duplicate Week Planner entry.\n    for duplicate in matches[1:]:\n        try:\n            await resources.async_delete_item(duplicate[\"id\"])\n            _LOGGER.info(\"Removed duplicate Week Planner Lovelace resource %s\", duplicate.get(CONF_URL))\n        except Exception as err:\n            _LOGGER.warning(\"Could not remove duplicate Week Planner resource %s: %s\", duplicate.get(CONF_URL), err)\n\n\n'''
text = text[:start] + new + text[end+1:]
path.write_text(text, encoding='utf-8')

for p in [Path('custom_components/week_planner/const.py'), Path('custom_components/week_planner/manifest.json'), Path('custom_components/week_planner/frontend/week-planner.js')]:
    s = p.read_text(encoding='utf-8').replace('0.5.3-dev.20', '0.5.3-dev.21')
    p.write_text(s, encoding='utf-8')
print('patched resource lifecycle and bumped dev.21')